"""Isaac Lab ArticulationCfg for arm4 (generated by cad2urdf)."""

import os

import isaaclab.sim as sim_utils
from isaaclab.actuators import ImplicitActuatorCfg
from isaaclab.assets.articulation import ArticulationCfg

_HERE = os.path.dirname(__file__)

ARM4_CFG = ArticulationCfg(
    spawn=sim_utils.UrdfFileCfg(
        asset_path=os.path.join(_HERE, "../arm4.urdf"),
        fix_base=True,
        merge_fixed_joints=True,
        # Collision comes from the URDF <collision> elements, which cad2urdf already made
        # convex (primitives / <=64-vertex hulls). The importer then only has to cook them.
        collision_from_visuals=False,
        collision_type="Convex Hull",
        self_collision=True,  # pairs to filter: see the SRDF disable_collisions list
        joint_drive=sim_utils.UrdfConverterCfg.JointDriveCfg(
            drive_type="force",
            target_type="position",
            gains=sim_utils.UrdfConverterCfg.JointDriveCfg.PDGainsCfg(stiffness=0.0, damping=0.0),
        ),
    ),
    init_state=ArticulationCfg.InitialStateCfg(
        joint_pos={"shoulder_yaw": 0, "shoulder_pitch": 0, "elbow": 0, "wrist_roll": 0, "finger_left": 0, "finger_right": 0},
    ),
    actuators={
        "shoulder_yaw": ImplicitActuatorCfg(
            joint_names_expr=["shoulder_yaw"],
            stiffness=200,
            damping=10,
            armature=0.01,
            friction=0.05,
            joint_effort_limit=40,
            joint_velocity_limit=3,
        ),
        "shoulder_pitch": ImplicitActuatorCfg(
            joint_names_expr=["shoulder_pitch"],
            stiffness=200,
            damping=10,
            armature=0.01,
            friction=0.05,
            joint_effort_limit=40,
            joint_velocity_limit=3,
        ),
        "elbow": ImplicitActuatorCfg(
            joint_names_expr=["elbow"],
            stiffness=200,
            damping=10,
            armature=0.01,
            friction=0.05,
            joint_effort_limit=20,
            joint_velocity_limit=3,
        ),
        "wrist_roll": ImplicitActuatorCfg(
            joint_names_expr=["wrist_roll"],
            stiffness=20,
            damping=1,
            armature=0.01,
            friction=0.05,
            joint_effort_limit=5,
            joint_velocity_limit=6,
        ),
        "finger_left": ImplicitActuatorCfg(
            joint_names_expr=["finger_left"],
            stiffness=500,
            damping=20,
            armature=0.001,
            friction=0.5,
            joint_effort_limit=20,
            joint_velocity_limit=0.1,
        ),
        "finger_right": ImplicitActuatorCfg(
            joint_names_expr=["finger_right"],
            stiffness=0,
            damping=0,
            armature=0.001,
            friction=0.5,
            joint_effort_limit=20,
            joint_velocity_limit=0.1,
        ),
    },
)
