"""SRDF writer with a sampled self-collision matrix (MoveIt Setup Assistant style).

The collision matrix is computed once, on the *collision* geometry, with
MuJoCo as the collision checker, then written into the SRDF and re-used by
every other target (MJCF <contact><exclude>, Isaac filtered pairs, SAPIEN
collision groups).

Reasons follow MoveIt: Adjacent (parent/child), Default (touching in the
default pose), Always (touching in >= 95 % of samples), Never (never touching
in any sample). Beware: SAPIEN/ManiSkill only honours reason="Default".
"""

from __future__ import annotations

import itertools
import tempfile
import xml.etree.ElementTree as ET
from collections import Counter
from pathlib import Path

import mujoco
import numpy as np

from .mjcf import _joint_order, build_mjcf
from .model import Robot


def expand_mimic(robot: Robot, q: dict[str, float]) -> dict[str, float]:
    q = dict(q)
    for j in robot.joints.values():
        if j.mimic and j.mimic["joint"] in q:
            q[j.name] = q[j.mimic["joint"]] * j.mimic.get("multiplier", 1.0) + j.mimic.get("offset", 0.0)
    return q


def collision_matrix(robot: Robot, mesh_dir: Path, samples: int = 5000, seed: int = 0):
    with tempfile.TemporaryDirectory() as tmp:
        xml_path = Path(tmp) / "probe.xml"
        build_mjcf(robot, meshdir=str(mesh_dir.resolve()), floor=False, filterparent=False,
                   collision_only=True, floating=False).write(xml_path, encoding="unicode")
        model = mujoco.MjModel.from_xml_path(str(xml_path))
    data = mujoco.MjData(model)
    joints = _joint_order(robot)
    body_name = [mujoco.mj_id2name(model, mujoco.mjtObj.mjOBJ_BODY, i) for i in range(model.nbody)]

    def contacts(q: dict[str, float]) -> set[tuple[str, str]]:
        q = expand_mimic(robot, q)
        data.qpos[:] = [q.get(j.name, 0.0) for j in joints]
        mujoco.mj_kinematics(model, data)
        mujoco.mj_collision(model, data)
        pairs = set()
        for c in data.contact[: data.ncon]:
            if c.dist < 0:  # real penetration, not just within margin
                a = body_name[model.geom_bodyid[c.geom1]]
                b = body_name[model.geom_bodyid[c.geom2]]
                pairs.add(tuple(sorted((a, b))))
        return pairs

    rng = np.random.default_rng(seed)
    default = contacts({})
    counts: Counter = Counter()
    free = [j for j in joints if not j.mimic]
    for _ in range(samples):
        q = {j.name: rng.uniform(*((-np.pi, np.pi) if j.type == "continuous" else (j.lower, j.upper)))
             for j in free}
        counts.update(contacts(q))

    adjacent = {tuple(sorted((j.parent, j.child))) for j in robot.joints.values()}
    result = {}
    for pair in itertools.combinations(sorted(robot.links), 2):
        if pair in adjacent:
            result[pair] = "Adjacent"
        elif pair in default:
            result[pair] = "Default"
        elif counts[pair] >= 0.95 * samples:
            result[pair] = "Always"
        elif counts[pair] == 0:
            result[pair] = "Never"
    stats = {"samples": samples, "pairs_seen_colliding": {f"{a}|{b}": n for (a, b), n in counts.items()}}
    return result, stats


def build_srdf(robot: Robot, disabled: dict[tuple[str, str], str]) -> ET.ElementTree:
    s = robot.spec.get("srdf") or {}
    s.setdefault("virtual_joint", {"name": "world_joint", "type": "floating" if robot.floating_base else "fixed",
                                   "parent_frame": "world", "child_link": robot.root})
    s.setdefault("passive_joints", [j.name for j in robot.moving_joints()
                                    if j.actuator.get("kind", "none") == "none" and not j.mimic])
    root = ET.Element("robot", name=robot.name)
    root.append(ET.Comment(" generated by cad2urdf; collision matrix sampled on collision geometry "))
    for gname, g in s.get("groups", {}).items():
        ge = ET.SubElement(root, "group", name=gname)
        if "chain" in g:
            ET.SubElement(ge, "chain", base_link=g["chain"][0], tip_link=g["chain"][1])
        for j in g.get("joints", []):
            ET.SubElement(ge, "joint", name=j)
        for l in g.get("links", []):
            ET.SubElement(ge, "link", name=l)
    for sname, st in s.get("group_states", {}).items():
        se = ET.SubElement(root, "group_state", name=sname, group=st["group"])
        for j, v in st["joints"].items():
            ET.SubElement(se, "joint", name=j, value=f"{v:.6g}")
    ee = s.get("end_effector")
    if ee:
        ET.SubElement(root, "end_effector", name=ee["name"], parent_link=ee["parent_link"], group=ee["group"],
                      parent_group=ee["parent_group"])
    vj = s.get("virtual_joint")
    if vj:
        ET.SubElement(root, "virtual_joint", name=vj["name"], type=vj["type"], parent_frame=vj["parent_frame"],
                      child_link=vj["child_link"])
    for pj in s.get("passive_joints", []):
        ET.SubElement(root, "passive_joint", name=pj)
    for (a, b), reason in sorted(disabled.items(), key=lambda kv: (kv[1], kv[0])):
        ET.SubElement(root, "disable_collisions", link1=a, link2=b, reason=reason)
    ET.indent(root)
    return ET.ElementTree(root)
