"""Simulator side files URDF can't express: Isaac Lab ArticulationCfg, ManiSkill agent class, Gazebo
ros2_control controllers.
"""

from __future__ import annotations

from pathlib import Path

from .model import Robot


def _actuated(robot: Robot):
    return [j for j in robot.moving_joints() if j.actuator.get("kind", "none") != "none"]


def _home(robot: Robot) -> dict[str, float]:
    """Joint positions of the SRDF "home" state (0 for unspecified joints, mimics expanded)."""
    from .srdf import expand_mimic

    home = robot.spec.get("srdf", {}).get("group_states", {}).get("home", {}).get("joints", {})
    return expand_mimic(robot, {j.name: home.get(j.name, 0.0) for j in robot.moving_joints()})


def isaaclab_cfg(robot: Robot, urdf_rel: str) -> str:
    home = _home(robot)
    lines = [
        f'"""Isaac Lab ArticulationCfg for {robot.name} (generated by cad2urdf)."""',
        "",
        "import os",
        "",
        "import isaaclab.sim as sim_utils",
        "from isaaclab.actuators import ImplicitActuatorCfg",
        "from isaaclab.assets.articulation import ArticulationCfg",
        "",
        "_HERE = os.path.dirname(__file__)",
        "",
        f"{robot.name.upper()}_CFG = ArticulationCfg(",
        "    spawn=sim_utils.UrdfFileCfg(",
        f'        asset_path=os.path.join(_HERE, "{urdf_rel}"),',
        f"        fix_base={not robot.floating_base},",
        "        merge_fixed_joints=True,",
        "        # Collision comes from the URDF <collision> elements, which cad2urdf already made",
        "        # convex (primitives / <=64-vertex hulls). The importer then only has to cook them.",
        "        collision_from_visuals=False,",
        '        collision_type="Convex Hull",',
        "        self_collision=True,  # pairs to filter: see the SRDF disable_collisions list",
        "        joint_drive=sim_utils.UrdfConverterCfg.JointDriveCfg(",
        '            drive_type="force",',
        '            target_type="position",',
        "            gains=sim_utils.UrdfConverterCfg.JointDriveCfg.PDGainsCfg(stiffness=0.0, damping=0.0),",
        "        ),",
        "    ),",
        "    init_state=ArticulationCfg.InitialStateCfg(",
        "        joint_pos={" + ", ".join(f'"{k}": {v:.4g}' for k, v in home.items()) + "},",
        "    ),",
        "    actuators={",
    ]
    for j in robot.moving_joints():
        a = j.actuator
        if a.get("kind", "none") == "none" and not j.mimic:
            continue
        kp, kv = (a.get("kp", 0.0), a.get("kv", 0.0)) if a.get("kind") != "none" else (0.0, 0.0)
        lines += [
            f'        "{j.name}": ImplicitActuatorCfg(',
            f'            joint_names_expr=["{j.name}"],',
            f"            stiffness={kp:.6g},",
            f"            damping={kv:.6g},",
            f"            armature={j.armature:.6g},",
            f"            friction={j.friction:.6g},",
            *([f"            joint_effort_limit={j.effort:.6g},"] if j.effort else []),
            *([f"            joint_velocity_limit={j.velocity:.6g},"] if j.velocity else []),
            "        ),",
        ]
    lines += ["    },", ")", ""]
    return "\n".join(lines)


def _groups(robot: Robot):
    """Split actuated joints into a plain PD group and one group per mimic leader."""
    act = _actuated(robot)
    followers = [j for j in robot.moving_joints() if j.mimic]
    leaders = {j.mimic["joint"] for j in followers}
    plain = [j for j in act if j.name not in leaders and not j.mimic]
    mimic_groups = [(robot.joints[l], [f for f in followers if f.mimic["joint"] == l]) for l in sorted(leaders)]
    return plain, mimic_groups


def _force(j) -> float:
    return j.effort if j.effort else 1e10  # ManiSkill's default "unlimited"


def maniskill_agent(robot: Robot, urdf_rel: str) -> str:
    from .srdf import expand_mimic

    plain, mimic_groups = _groups(robot)
    fr = robot.spec.get("contact", {}).get("friction", [1.0])[0]
    states = robot.spec.get("srdf", {}).get("group_states", {})
    order = [j.name for j in robot.moving_joints()]  # == SAPIEN active-joint order
    kf = []
    for name, st in states.items():
        q = expand_mimic(robot, {**{n: 0.0 for n in order}, **st["joints"]})
        kf.append(f'        {name}=Keyframe(qpos=np.array([{", ".join(f"{q[n]:.4g}" for n in order)}]), pose=sapien.Pose()),')
    body = []
    if plain:
        body += [
            "        arm = PDJointPosControllerConfig(",
            f"            {[j.name for j in plain]},",
            "            lower=None, upper=None,",
            f"            stiffness={[j.actuator.get('kp', 0.0) for j in plain]},",
            f"            damping={[j.actuator.get('kv', 0.0) for j in plain]},",
            f"            force_limit={[_force(j) for j in plain]},",
            "            normalize_action=False,",
            "        )",
        ]
    names = ["arm"] if plain else []
    for i, (lead, fol) in enumerate(mimic_groups):
        g = "gripper" if len(mimic_groups) == 1 else f"mimic_{lead.name}"
        names.append(g)
        mimic_map = {f.name: {"joint": lead.name, "multiplier": f.mimic.get("multiplier", 1.0),
                              "offset": f.mimic.get("offset", 0.0)} for f in fol}
        body += [
            f"        {g} = PDJointPosMimicControllerConfig(",
            f"            {[lead.name] + [f.name for f in fol]},",
            f"            lower={lead.lower}, upper={lead.upper},",
            f"            stiffness={lead.actuator.get('kp', 0.0)}, damping={lead.actuator.get('kv', 0.0)},",
            f"            force_limit={_force(lead)},",
            f"            mimic={mimic_map},",
            "            normalize_action=False,  # targets in joint units (rad / m), not [-1, 1]",
            "        )",
        ]
    body.append(f"        return dict(pd_joint_pos=dict({', '.join(f'{n}={n}' for n in names)}))")
    return "\n".join([
        f'"""ManiSkill 3 agent for {robot.name} (generated by cad2urdf)."""',
        "",
        "import os",
        "",
        "import numpy as np",
        "import sapien",
        "",
        "from mani_skill.agents.base_agent import BaseAgent, Keyframe",
        "from mani_skill.agents.controllers import PDJointPosControllerConfig, PDJointPosMimicControllerConfig",
        "from mani_skill.agents.registration import register_agent",
        "",
        "",
        "@register_agent()",
        f"class {''.join(w.capitalize() for w in robot.name.split('_'))}(BaseAgent):",
        f'    uid = "{robot.name}"',
        f'    urdf_path = os.path.join(os.path.dirname(__file__), "{urdf_rel}")',
        "    # SAPIEN reads the SRDF next to the URDF automatically, but only reason=\"Default\" pairs.",
        "    load_multiple_collisions = False  # every collision STL is already a single convex piece",
        f"    fix_root_link = {not robot.floating_base}",
        "    urdf_config = dict(",
        f"        _materials=dict(default=dict(static_friction={fr}, dynamic_friction={fr}, restitution=0.0)),",
        "        link={" + ", ".join(f'"{l}": dict(material="default")' for l in robot.links) + "},",
        "    )",
        "    keyframes = dict(",
        *kf,
        "    )",
        "",
        "    @property",
        "    def _controller_configs(self):",
        *body,
        "",
    ])


def gazebo_controllers(robot: Robot) -> str:
    plain, mimic_groups = _groups(robot)
    lines = [
        "# ros2_control controllers for gz_ros2_control (generated by cad2urdf)",
        "controller_manager:",
        "  ros__parameters:",
        "    update_rate: 500",
        "    joint_state_broadcaster: {type: joint_state_broadcaster/JointStateBroadcaster}",
    ]
    if plain:
        lines.append("    arm_controller: {type: joint_trajectory_controller/JointTrajectoryController}")
    for lead, _ in mimic_groups:
        lines.append(f"    {lead.name}_controller: {{type: position_controllers/GripperActionController}}")
    if plain:
        lines += ["", "arm_controller:", "  ros__parameters:", f"    joints: [{', '.join(j.name for j in plain)}]",
                  "    command_interfaces: [position]", "    state_interfaces: [position, velocity]"]
    for lead, _ in mimic_groups:
        lines += ["", f"{lead.name}_controller:", "  ros__parameters:", f"    joint: {lead.name}"]
    return "\n".join(lines) + "\n"


def write_targets(robot: Robot, out: Path) -> None:
    (out / "isaaclab").mkdir(parents=True, exist_ok=True)
    (out / "maniskill").mkdir(parents=True, exist_ok=True)
    (out / "gazebo" / "config").mkdir(parents=True, exist_ok=True)
    (out / "isaaclab" / f"{robot.name}_cfg.py").write_text(isaaclab_cfg(robot, f"../{robot.name}.urdf"))
    (out / "maniskill" / f"{robot.name}_agent.py").write_text(maniskill_agent(robot, f"../{robot.name}.urdf"))
    (out / "gazebo" / "config" / "controllers.yaml").write_text(gazebo_controllers(robot))
