"""Simulator-specific side files that URDF cannot express.

* Isaac Lab:   ArticulationCfg (UrdfFileCfg import options + actuator groups)
* ManiSkill:   BaseAgent subclass (controllers, keyframes, materials)
* Gazebo:      ros2_control controllers.yaml for gz_ros2_control

These are emitted as text templates filled from the IR. They follow the APIs of
Isaac Lab `main` and ManiSkill 3 as of Sep 2026 but could not be executed in
this environment (no Isaac Sim / GPU); treat them as starting points.
"""

from __future__ import annotations

from pathlib import Path

from .model import Robot


def _actuated(robot: Robot):
    return [j for j in robot.joints.values() if j.actuator.get("kind", "none") != "none"]


def _home(robot: Robot) -> dict[str, float]:
    """Joint positions of the SRDF "home" state (0 for unspecified joints, mimics expanded)."""
    from .srdf import expand_mimic

    home = robot.spec.get("srdf", {}).get("group_states", {}).get("home", {}).get("joints", {})
    return expand_mimic(robot, {j: home.get(j, 0.0) for j in robot.joints})


def isaaclab_cfg(robot: Robot, urdf_rel: str) -> str:
    home = _home(robot)
    lines = [
        f'"""Isaac Lab ArticulationCfg for {robot.name} (generated by cad2urdf)."""',
        "",
        "import os",
        "",
        "import isaaclab.sim as sim_utils",
        "from isaaclab.actuators import ImplicitActuatorCfg",
        "from isaaclab.assets.articulation import ArticulationCfg",
        "",
        "_HERE = os.path.dirname(__file__)",
        "",
        f"{robot.name.upper()}_CFG = ArticulationCfg(",
        "    spawn=sim_utils.UrdfFileCfg(",
        f'        asset_path=os.path.join(_HERE, "{urdf_rel}"),',
        "        fix_base=True,",
        "        merge_fixed_joints=True,",
        "        # Collision comes from the URDF <collision> elements, which cad2urdf already made",
        "        # convex (primitives / <=64-vertex hulls). The importer then only has to cook them.",
        "        collision_from_visuals=False,",
        '        collision_type="Convex Hull",',
        "        self_collision=True,  # pairs to filter: see the SRDF disable_collisions list",
        "        joint_drive=sim_utils.UrdfConverterCfg.JointDriveCfg(",
        '            drive_type="force",',
        '            target_type="position",',
        "            gains=sim_utils.UrdfConverterCfg.JointDriveCfg.PDGainsCfg(stiffness=0.0, damping=0.0),",
        "        ),",
        "    ),",
        "    init_state=ArticulationCfg.InitialStateCfg(",
        "        joint_pos={" + ", ".join(f'"{k}": {v:.4g}' for k, v in home.items()) + "},",
        "    ),",
        "    actuators={",
    ]
    for j in robot.joints.values():
        a = j.actuator
        if a.get("kind", "none") == "none" and not j.mimic:
            continue
        kp, kv = (a.get("kp", 0.0), a.get("kv", 0.0)) if a.get("kind") != "none" else (0.0, 0.0)
        lines += [
            f'        "{j.name}": ImplicitActuatorCfg(',
            f'            joint_names_expr=["{j.name}"],',
            f"            stiffness={kp:.6g},",
            f"            damping={kv:.6g},",
            f"            armature={j.armature:.6g},",
            f"            friction={j.friction:.6g},",
            f"            joint_effort_limit={j.effort:.6g},",
            f"            joint_velocity_limit={j.velocity:.6g},",
            "        ),",
        ]
    lines += ["    },", ")", ""]
    return "\n".join(lines)


def maniskill_agent(robot: Robot, urdf_rel: str) -> str:
    act = _actuated(robot)
    mimic = [j for j in robot.joints.values() if j.mimic]
    fr = robot.spec.get("contact", {}).get("friction", [1.0])[0]
    states = robot.spec.get("srdf", {}).get("group_states", {})
    from .srdf import expand_mimic

    order = [j.name for j in robot.joints.values()]  # URDF joint order; ManiSkill uses active joints
    kf = []
    for name in ("home", "ready"):
        if name in states:
            q = expand_mimic(robot, {**{j: 0.0 for j in robot.joints}, **states[name]["joints"]})
            kf.append(f'        {name}=Keyframe(qpos=np.array([{", ".join(f"{q[n]:.4g}" for n in order)}]), pose=sapien.Pose()),')
    arm = [j for j in act if j.type == "revolute"]
    grip = [j for j in act if j.type == "prismatic"]
    g0 = grip[0] if grip else None
    mimic_map = {j.name: {"joint": j.mimic["joint"]} for j in mimic}
    return "\n".join([
        f'"""ManiSkill 3 agent for {robot.name} (generated by cad2urdf)."""',
        "",
        "import os",
        "",
        "import numpy as np",
        "import sapien",
        "",
        "from mani_skill.agents.base_agent import BaseAgent, Keyframe",
        "from mani_skill.agents.controllers import PDJointPosControllerConfig, PDJointPosMimicControllerConfig",
        "from mani_skill.agents.registration import register_agent",
        "",
        "",
        "@register_agent()",
        f"class {robot.name.capitalize()}(BaseAgent):",
        f'    uid = "{robot.name}"',
        f'    urdf_path = os.path.join(os.path.dirname(__file__), "{urdf_rel}")',
        "    # SAPIEN reads the SRDF next to the URDF automatically, but only reason=\"Default\" pairs.",
        "    load_multiple_collisions = False  # every collision STL is already a single convex piece",
        "    fix_root_link = True",
        "    urdf_config = dict(",
        f"        _materials=dict(default=dict(static_friction={fr}, dynamic_friction={fr}, restitution=0.0)),",
        "        link={" + ", ".join(f'"{l}": dict(material="default")' for l in robot.links) + "},",
        "    )",
        "    keyframes = dict(",
        *kf,
        "    )",
        "",
        "    @property",
        "    def _controller_configs(self):",
        "        arm = PDJointPosControllerConfig(",
        f"            {[j.name for j in arm]},",
        "            lower=None, upper=None,",
        f"            stiffness={[j.actuator['kp'] for j in arm]},",
        f"            damping={[j.actuator.get('kv', 0.0) for j in arm]},",
        f"            force_limit={[j.effort for j in arm]},",
        "            normalize_action=False,",
        "        )",
        "        gripper = PDJointPosMimicControllerConfig(",
        f"            {[g0.name] + [j.name for j in mimic] if g0 else []},",
        f"            lower={g0.lower if g0 else 0}, upper={g0.upper if g0 else 0},",
        f"            stiffness={g0.actuator['kp'] if g0 else 0}, damping={g0.actuator.get('kv', 0) if g0 else 0},",
        f"            force_limit={g0.effort if g0 else 0},",
        f"            mimic={mimic_map},",
        "            normalize_action=False,",
        "        )",
        "        return dict(pd_joint_pos=dict(arm=arm, gripper=gripper))",
        "",
    ])


def gazebo_controllers(robot: Robot) -> str:
    act = _actuated(robot)
    arm = [j.name for j in act if j.type == "revolute"]
    grip = [j.name for j in act if j.type == "prismatic"]
    return "\n".join([
        "# ros2_control controllers for gz_ros2_control (generated by cad2urdf)",
        "controller_manager:",
        "  ros__parameters:",
        "    update_rate: 500",
        "    joint_state_broadcaster: {type: joint_state_broadcaster/JointStateBroadcaster}",
        "    arm_controller: {type: joint_trajectory_controller/JointTrajectoryController}",
        "    gripper_controller: {type: position_controllers/GripperActionController}",
        "",
        "arm_controller:",
        "  ros__parameters:",
        f"    joints: [{', '.join(arm)}]",
        "    command_interfaces: [position]",
        "    state_interfaces: [position, velocity]",
        "",
        "gripper_controller:",
        "  ros__parameters:",
        f"    joint: {grip[0] if grip else ''}",
        "",
    ])


def write_targets(robot: Robot, out: Path) -> None:
    (out / "isaaclab").mkdir(parents=True, exist_ok=True)
    (out / "maniskill").mkdir(parents=True, exist_ok=True)
    (out / "gazebo" / "config").mkdir(parents=True, exist_ok=True)
    (out / "isaaclab" / f"{robot.name}_cfg.py").write_text(isaaclab_cfg(robot, f"../{robot.name}.urdf"))
    (out / "maniskill" / f"{robot.name}_agent.py").write_text(maniskill_agent(robot, f"../{robot.name}.urdf"))
    (out / "gazebo" / "config" / "controllers.yaml").write_text(gazebo_controllers(robot))
