"""URDF writer (neutral flavour + Gazebo/ros2_control flavour)."""

from __future__ import annotations

import xml.etree.ElementTree as ET
from pathlib import Path


from .model import Robot
from .util import fmt, rpy




MAX_VISUAL_FACES = 100_000  # per STL file; MuJoCo rejects files over 200k triangles


def budget_mesh(mesh, max_faces: int = MAX_VISUAL_FACES):
    """Quadric-decimate a mesh to at most ``max_faces`` triangles (unchanged if already within budget)."""
    if len(mesh.faces) <= max_faces:
        return mesh
    try:
        out = mesh.simplify_quadric_decimation(face_count=max_faces)
    except Exception:  # noqa: BLE001  (no decimator installed: keep the MuJoCo limit at least)
        out = mesh.submesh([mesh.area_faces.argsort()[::-1][:max_faces]], append=True)
    return out if len(out.faces) else mesh


def split_heavy_visuals(robot: Robot, max_faces: int = MAX_VISUAL_FACES) -> None:
    """Split visual meshes over ``max_faces`` into several files by connected parts (decimation stalls on
    links fused from many parts); a single part over budget is decimated."""
    import trimesh

    for link in robot.links.values():
        new, mats = {}, {}
        for key, mesh in link.visuals.items():
            if len(mesh.faces) <= max_faces:
                new[key], mats[key] = mesh, link.material(key)
                continue
            chunks, cur, n = [], [], 0
            for comp in sorted(mesh.split(only_watertight=False), key=lambda c: -len(c.faces)):
                comp = budget_mesh(comp, max_faces)
                if n + len(comp.faces) > max_faces and cur:
                    chunks.append(cur)
                    cur, n = [], 0
                cur.append(comp)
                n += len(comp.faces)
            if cur:
                chunks.append(cur)
            for i, ch in enumerate(chunks):
                new[f"{key}_{i}"] = trimesh.util.concatenate(ch)
                mats[f"{key}_{i}"] = link.material(key)
        link.visuals, link.visual_materials = new, mats


def export_meshes(robot: Robot, mesh_dir: Path) -> None:
    (mesh_dir / "visual").mkdir(parents=True, exist_ok=True)
    (mesh_dir / "collision").mkdir(parents=True, exist_ok=True)
    split_heavy_visuals(robot)
    for link in robot.links.values():
        for mat, mesh in link.visuals.items():
            budget_mesh(mesh).export(mesh_dir / "visual" / f"{link.name}_{mat}.stl")
        for i, g in enumerate(link.collisions):
            if g.kind == "mesh":
                g.mesh.export(mesh_dir / "collision" / f"{link.name}_{i}.stl")


def _origin(parent: ET.Element, xyz, rpy_=(0, 0, 0)):
    ET.SubElement(parent, "origin", xyz=fmt(xyz), rpy=fmt(rpy_))


def build_urdf(robot: Robot, mesh_prefix: str = "meshes", flavour: str = "neutral") -> ET.ElementTree:
    root = ET.Element("robot", name=robot.name)
    root.append(ET.Comment(" generated by cad2urdf from " + robot.spec["source"] + " — do not edit by hand "))
    for mat, rgba in robot.used_materials().items():
        ET.SubElement(ET.SubElement(root, "material", name=mat), "color", rgba=rgba)

    if flavour == "gazebo" and not robot.floating_base:  # anchor the fixed base to the world
        ET.SubElement(root, "link", name="world")
        j = ET.SubElement(root, "joint", name="world_joint", type="fixed")
        ET.SubElement(j, "parent", link="world")
        ET.SubElement(j, "child", link=robot.root)

    for name in robot.ordered_links():
        link = robot.links[name]
        el = ET.SubElement(root, "link", name=name)
        inertial = ET.SubElement(el, "inertial")
        _origin(inertial, link.com)
        ET.SubElement(inertial, "mass", value=f"{link.mass:.6g}")
        I = link.inertia
        ET.SubElement(inertial, "inertia", ixx=f"{I[0,0]:.6g}", ixy=f"{I[0,1]:.6g}", ixz=f"{I[0,2]:.6g}",
                      iyy=f"{I[1,1]:.6g}", iyz=f"{I[1,2]:.6g}", izz=f"{I[2,2]:.6g}")
        for mat in link.visuals:
            vis = ET.SubElement(el, "visual", name=f"{name}_{mat}")
            _origin(vis, (0, 0, 0))
            ET.SubElement(ET.SubElement(vis, "geometry"), "mesh", filename=f"{mesh_prefix}/visual/{name}_{mat}.stl")
            ET.SubElement(vis, "material", name=link.material(mat))
        for i, g in enumerate(link.collisions):
            col = ET.SubElement(el, "collision", name=f"{name}_collision_{i}")
            _origin(col, g.transform[:3, 3], rpy(g.transform))
            geo = ET.SubElement(col, "geometry")
            if g.kind == "box":
                ET.SubElement(geo, "box", size=fmt(g.size))
            elif g.kind == "cylinder":
                ET.SubElement(geo, "cylinder", radius=f"{g.size[0]:.6g}", length=f"{g.size[1]:.6g}")
            elif g.kind == "sphere":
                ET.SubElement(geo, "sphere", radius=f"{g.size[0]:.6g}")
            else:
                ET.SubElement(geo, "mesh", filename=f"{mesh_prefix}/collision/{name}_{i}.stl")

    for j in robot.joints.values():
        el = ET.SubElement(root, "joint", name=j.name, type=j.type)
        xyz, R = robot.child_in_parent(j)
        _origin(el, xyz, rpy(R))
        ET.SubElement(el, "parent", link=j.parent)
        ET.SubElement(el, "child", link=j.child)
        if j.type == "fixed":
            continue
        ET.SubElement(el, "axis", xyz=fmt(robot.axis_local(j)))
        if j.type in ("revolute", "prismatic"):
            ET.SubElement(el, "limit", lower=f"{j.lower:.6g}", upper=f"{j.upper:.6g}",
                          effort=f"{j.effort:.6g}", velocity=f"{j.velocity:.6g}")
        elif j.effort or j.velocity:  # continuous
            ET.SubElement(el, "limit", effort=f"{j.effort:.6g}", velocity=f"{j.velocity:.6g}")
        # URDF has no armature/rotor-inertia field; it lives in the sim-specific outputs.
        ET.SubElement(el, "dynamics", damping=f"{j.damping:.6g}", friction=f"{j.friction:.6g}")
        if j.mimic:
            ET.SubElement(el, "mimic", joint=j.mimic["joint"], multiplier=f"{j.mimic.get('multiplier', 1.0):.6g}",
                          offset=f"{j.mimic.get('offset', 0.0):.6g}")

    if flavour == "gazebo":
        _gazebo_extensions(root, robot)
    ET.indent(root)
    return ET.ElementTree(root)


def _gazebo_extensions(root: ET.Element, robot: Robot) -> None:
    """<gazebo> surface tags + a ros2_control block for gz_ros2_control."""
    mu = robot.spec.get("contact", {}).get("friction", [1.0])[0]
    for name in robot.links:
        g = ET.SubElement(root, "gazebo", reference=name)
        ET.SubElement(g, "mu1").text = f"{mu}"
        ET.SubElement(g, "mu2").text = f"{mu}"
        ET.SubElement(g, "kp").text = "1e6"
        ET.SubElement(g, "kd").text = "100"
    rc = ET.SubElement(root, "ros2_control", name="GazeboSimSystem", type="system")
    ET.SubElement(ET.SubElement(rc, "hardware"), "plugin").text = "gz_ros2_control/GazeboSimSystem"
    for j in robot.moving_joints():
        je = ET.SubElement(rc, "joint", name=j.name)
        if j.mimic:
            ET.SubElement(je, "param", name="mimic").text = j.mimic["joint"]
            ET.SubElement(je, "param", name="multiplier").text = str(j.mimic.get("multiplier", 1.0))
        else:
            ci = ET.SubElement(je, "command_interface", name="position")
            if j.type != "continuous":
                ET.SubElement(ci, "param", name="min").text = f"{j.lower:.6g}"
                ET.SubElement(ci, "param", name="max").text = f"{j.upper:.6g}"
        ET.SubElement(je, "state_interface", name="position")
        ET.SubElement(je, "state_interface", name="velocity")
    g = ET.SubElement(root, "gazebo")
    p = ET.SubElement(g, "plugin", filename="gz_ros2_control-system", name="gz_ros2_control::GazeboSimROS2ControlPlugin")
    ET.SubElement(p, "parameters").text = f"$(find {robot.name}_description)/config/controllers.yaml"


def write_urdf(robot: Robot, path: Path, **kw) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    build_urdf(robot, **kw).write(path, encoding="unicode", xml_declaration=True)
