"""Writers for every target.

* URDF (neutral and Gazebo flavour) and mesh export
* MJCF: armature, actuators, mimic and loop equalities, contact excludes, keyframes (what URDF can't carry)
* SRDF with a self-collision matrix sampled in MuJoCo on the collision geometry (reasons follow MoveIt:
  Adjacent, Default, Always, Never; SAPIEN/ManiSkill only honour Default); it also feeds the MJCF excludes
* side files URDF can't express: Isaac Lab ArticulationCfg, ManiSkill agent class, Gazebo ros2_control
"""

from __future__ import annotations

import itertools
import tempfile
import xml.etree.ElementTree as ET
from collections import Counter
from pathlib import Path

import mujoco
import numpy as np

from .geometry import budget_mesh, split_heavy_visuals
from .model import Robot
from .util import fmt, quat, rpy


def export_meshes(robot: Robot, mesh_dir: Path) -> None:
    (mesh_dir / "visual").mkdir(parents=True, exist_ok=True)
    (mesh_dir / "collision").mkdir(parents=True, exist_ok=True)
    split_heavy_visuals(robot)
    for link in robot.links.values():
        for mat, mesh in link.visuals.items():
            budget_mesh(mesh).export(mesh_dir / "visual" / f"{link.name}_{mat}.stl")
        for i, g in enumerate(link.collisions):
            if g.kind == "mesh":
                g.mesh.export(mesh_dir / "collision" / f"{link.name}_{i}.stl")


def _origin(parent: ET.Element, xyz, rpy_=(0, 0, 0)):
    ET.SubElement(parent, "origin", xyz=fmt(xyz), rpy=fmt(rpy_))


def build_urdf(robot: Robot, mesh_prefix: str = "meshes", flavour: str = "neutral") -> ET.ElementTree:
    root = ET.Element("robot", name=robot.name)
    root.append(ET.Comment(" generated by cad2urdf from " + robot.spec["source"] + " — do not edit by hand "))
    for mat, rgba in robot.used_materials().items():
        ET.SubElement(ET.SubElement(root, "material", name=mat), "color", rgba=rgba)

    if flavour == "gazebo" and not robot.floating_base:  # anchor the fixed base to the world
        ET.SubElement(root, "link", name="world")
        j = ET.SubElement(root, "joint", name="world_joint", type="fixed")
        ET.SubElement(j, "parent", link="world")
        ET.SubElement(j, "child", link=robot.root)

    for name in robot.ordered_links():
        link = robot.links[name]
        el = ET.SubElement(root, "link", name=name)
        inertial = ET.SubElement(el, "inertial")
        _origin(inertial, link.com)
        ET.SubElement(inertial, "mass", value=f"{link.mass:.6g}")
        I = link.inertia
        ET.SubElement(inertial, "inertia", ixx=f"{I[0,0]:.6g}", ixy=f"{I[0,1]:.6g}", ixz=f"{I[0,2]:.6g}",
                      iyy=f"{I[1,1]:.6g}", iyz=f"{I[1,2]:.6g}", izz=f"{I[2,2]:.6g}")
        for mat in link.visuals:
            vis = ET.SubElement(el, "visual", name=f"{name}_{mat}")
            _origin(vis, (0, 0, 0))
            ET.SubElement(ET.SubElement(vis, "geometry"), "mesh", filename=f"{mesh_prefix}/visual/{name}_{mat}.stl")
            ET.SubElement(vis, "material", name=link.material(mat))
        for i, g in enumerate(link.collisions):
            col = ET.SubElement(el, "collision", name=f"{name}_collision_{i}")
            _origin(col, g.transform[:3, 3], rpy(g.transform))
            geo = ET.SubElement(col, "geometry")
            if g.kind == "box":
                ET.SubElement(geo, "box", size=fmt(g.size))
            elif g.kind == "cylinder":
                ET.SubElement(geo, "cylinder", radius=f"{g.size[0]:.6g}", length=f"{g.size[1]:.6g}")
            elif g.kind == "sphere":
                ET.SubElement(geo, "sphere", radius=f"{g.size[0]:.6g}")
            else:
                ET.SubElement(geo, "mesh", filename=f"{mesh_prefix}/collision/{name}_{i}.stl")

    for j in robot.joints.values():
        el = ET.SubElement(root, "joint", name=j.name, type=j.type)
        xyz, R = robot.child_in_parent(j)
        _origin(el, xyz, rpy(R))
        ET.SubElement(el, "parent", link=j.parent)
        ET.SubElement(el, "child", link=j.child)
        if j.type == "fixed":
            continue
        ET.SubElement(el, "axis", xyz=fmt(robot.axis_local(j)))
        if j.type in ("revolute", "prismatic"):
            ET.SubElement(el, "limit", lower=f"{j.lower:.6g}", upper=f"{j.upper:.6g}",
                          effort=f"{j.effort:.6g}", velocity=f"{j.velocity:.6g}")
        elif j.effort or j.velocity:  # continuous
            ET.SubElement(el, "limit", effort=f"{j.effort:.6g}", velocity=f"{j.velocity:.6g}")
        # URDF has no armature/rotor-inertia field; it lives in the sim-specific outputs.
        ET.SubElement(el, "dynamics", damping=f"{j.damping:.6g}", friction=f"{j.friction:.6g}")
        if j.mimic:
            ET.SubElement(el, "mimic", joint=j.mimic["joint"], multiplier=f"{j.mimic.get('multiplier', 1.0):.6g}",
                          offset=f"{j.mimic.get('offset', 0.0):.6g}")

    if flavour == "gazebo":
        _gazebo_extensions(root, robot)
    ET.indent(root)
    return ET.ElementTree(root)


def _gazebo_extensions(root: ET.Element, robot: Robot) -> None:
    """<gazebo> surface tags + a ros2_control block for gz_ros2_control."""
    mu = robot.spec.get("contact", {}).get("friction", [1.0])[0]
    for name in robot.links:
        g = ET.SubElement(root, "gazebo", reference=name)
        ET.SubElement(g, "mu1").text = f"{mu}"
        ET.SubElement(g, "mu2").text = f"{mu}"
        ET.SubElement(g, "kp").text = "1e6"
        ET.SubElement(g, "kd").text = "100"
    rc = ET.SubElement(root, "ros2_control", name="GazeboSimSystem", type="system")
    ET.SubElement(ET.SubElement(rc, "hardware"), "plugin").text = "gz_ros2_control/GazeboSimSystem"
    for j in robot.moving_joints():
        je = ET.SubElement(rc, "joint", name=j.name)
        if j.mimic:
            ET.SubElement(je, "param", name="mimic").text = j.mimic["joint"]
            ET.SubElement(je, "param", name="multiplier").text = str(j.mimic.get("multiplier", 1.0))
        else:
            ci = ET.SubElement(je, "command_interface", name="position")
            if j.type != "continuous":
                ET.SubElement(ci, "param", name="min").text = f"{j.lower:.6g}"
                ET.SubElement(ci, "param", name="max").text = f"{j.upper:.6g}"
        ET.SubElement(je, "state_interface", name="position")
        ET.SubElement(je, "state_interface", name="velocity")
    g = ET.SubElement(root, "gazebo")
    p = ET.SubElement(g, "plugin", filename="gz_ros2_control-system", name="gz_ros2_control::GazeboSimROS2ControlPlugin")
    ET.SubElement(p, "parameters").text = f"$(find {robot.name}_description)/config/controllers.yaml"


def write_urdf(robot: Robot, path: Path, **kw) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    build_urdf(robot, **kw).write(path, encoding="unicode", xml_declaration=True)


MIN_MASS = 1e-4  # kg: MuJoCo rejects massless moving bodies (URDF dummy links often have mass 0)


def _mass_inertia(link) -> tuple[float, np.ndarray]:
    if link.mass > 0 and np.linalg.eigvalsh(link.inertia).min() > 0:
        return link.mass, link.inertia
    m = max(link.mass, MIN_MASS)
    return m, np.eye(3) * m * 1e-4  # a 1 cm-ish sphere-like inertia


TIMESTEP = 0.002


def _servo_dynamics(j, dt: float) -> tuple[float, float]:
    """(damping, armature) that keep a position servo stable and inside its speed limit.

    Armature: an explicit spring kp on a tiny inertia oscillates when sqrt(kp/I)*dt is not small, so the
    reflected inertia is at least 16*kp*dt^2. Damping: the torque clip does not bound speed (kp*error can
    dwarf the effort), so damping of effort/velocity makes the speed limit the terminal speed.
    """
    kp = j.actuator.get("kp", 0.0) if j.actuator.get("kind", "none") == "position" else 0.0
    damping = max(j.damping, j.effort / j.velocity) if j.effort and j.velocity and kp else j.damping
    return damping, max(j.armature, 16 * kp * dt * dt)


def build_mjcf(
    robot: Robot,
    meshdir: str = "../meshes",
    excludes: list[tuple[str, str]] = (),
    keyframes: dict[str, dict[str, float]] | None = None,
    floor: bool = True,
    filterparent: bool = True,
    collision_only: bool = False,
    floating: bool = True,
) -> ET.ElementTree:
    spec = robot.spec
    fr = spec.get("contact", {}).get("friction", [1.0, 0.005, 0.0001])
    root = ET.Element("mujoco", model=robot.name)
    ET.SubElement(root, "compiler", angle="radian", meshdir=meshdir, autolimits="true")
    opt = ET.SubElement(root, "option", timestep=str(TIMESTEP), integrator="implicitfast")
    if not filterparent:
        ET.SubElement(opt, "flag", filterparent="disable")

    default = ET.SubElement(root, "default")
    vis = ET.SubElement(default, "default", {"class": "visual"})
    ET.SubElement(vis, "geom", contype="0", conaffinity="0", group="2", density="0")
    col = ET.SubElement(default, "default", {"class": "collision"})
    ET.SubElement(col, "geom", group="3", friction=fmt(fr), condim="4", density="0", rgba="0.2 0.6 1 0.4")

    asset = ET.SubElement(root, "asset")
    for mat, rgba in robot.used_materials().items():
        ET.SubElement(asset, "material", name=mat, rgba=rgba)
    for link in robot.links.values():
        if not collision_only:
            for key in link.visuals:
                ET.SubElement(asset, "mesh", name=f"{link.name}_{key}", file=f"visual/{link.name}_{key}.stl")
        for i, g in enumerate(link.collisions):
            if g.kind == "mesh":
                ET.SubElement(asset, "mesh", name=f"{link.name}_col{i}", file=f"collision/{link.name}_{i}.stl")

    world = ET.SubElement(root, "worldbody")
    if floor:
        ET.SubElement(world, "light", pos="0 0 3", dir="0 0 -1", directional="true")
        # floor just below the robot's lowest point at q=0, so CAD coordinates stay untouched
        zs = [(l.rotation @ m.vertices.T).T[:, 2].min() + l.origin[2]
              for l in robot.links.values() for m in l.visuals.values() if len(m.vertices)]
        z_floor = min(0.0, min(zs) - 0.01) if zs else 0.0
        ET.SubElement(world, "geom", name="floor", type="plane", size="10 10 0.1", pos=fmt((0, 0, z_floor)),
                      rgba="0.9 0.9 0.9 1")

    def add_body(parent_el: ET.Element, name: str):
        link = robot.links[name]
        j = robot.parent_joint(name)
        if j is None:
            pos, R = link.origin, link.rotation
        else:
            pos, R = robot.child_in_parent(j)
        T = np.eye(4)
        T[:3, :3] = R
        body = ET.SubElement(parent_el, "body", name=name, pos=fmt(pos), quat=quat(T))
        mass, I = _mass_inertia(link)
        ET.SubElement(body, "inertial", pos=fmt(link.com), mass=f"{mass:.6g}",
                      fullinertia=fmt((I[0, 0], I[1, 1], I[2, 2], I[0, 1], I[0, 2], I[1, 2])))
        if j is None and robot.floating_base and floating:
            ET.SubElement(body, "freejoint", name="root")
        if j is not None and j.type != "fixed":
            damping, armature = _servo_dynamics(j, TIMESTEP)
            attrs = dict(name=j.name, type="slide" if j.type == "prismatic" else "hinge",
                         axis=fmt(robot.axis_local(j)),
                         damping=f"{damping:.6g}", frictionloss=f"{j.friction:.6g}", armature=f"{armature:.6g}")
            if j.type != "continuous":
                attrs["range"] = fmt((j.lower, j.upper))
            if j.effort:
                attrs["actuatorfrcrange"] = fmt((-j.effort, j.effort))
            ET.SubElement(body, "joint", attrs)
        if not collision_only:
            for key in link.visuals:
                ET.SubElement(body, "geom", {"class": "visual", "type": "mesh", "mesh": f"{name}_{key}",
                                             "material": link.material(key)})
        for i, g in enumerate(link.collisions):
            a = {"class": "collision", "name": f"{name}_col{i}"}
            if g.kind == "mesh":
                a.update(type="mesh", mesh=f"{name}_col{i}")
            else:
                a.update(pos=fmt(g.transform[:3, 3]), quat=quat(g.transform))
                if g.kind == "box":
                    a.update(type="box", size=fmt(np.array(g.size) / 2))
                elif g.kind == "cylinder":
                    a.update(type="cylinder", size=fmt((g.size[0], g.size[1] / 2)))
                else:
                    a.update(type="sphere", size=fmt(g.size[:1]))
            ET.SubElement(body, "geom", a)
        for child in [jj.child for jj in robot.joints.values() if jj.parent == name]:
            add_body(body, child)

    add_body(world, robot.root)
    # a site at the tool centre point, handy for IK / task code
    ee = spec.get("srdf", {}).get("end_effector")
    tcp = world.find(f".//body[@name='{ee['parent_link']}']") if ee else None
    if tcp is not None:
        ET.SubElement(tcp, "site", name="tcp", pos="0 0 0.12", size="0.005")

    excludes = list(excludes or []) + [(c["link1"], c["link2"]) for c in robot.closures]
    if excludes:
        contact = ET.SubElement(root, "contact")
        for a, b in dict.fromkeys(tuple(e) for e in excludes):
            ET.SubElement(contact, "exclude", body1=a, body2=b)

    mimics = [j for j in robot.joints.values() if j.mimic]
    if mimics or robot.closures:
        eq = ET.SubElement(root, "equality")
        for c in robot.closures:  # closed loops: a point constraint at the closing mate
            ET.SubElement(eq, "connect", name=c["name"], body1=c["link1"], body2=c["link2"], anchor=fmt(c["anchor1"]))
        for j in mimics:
            m = j.mimic
            ET.SubElement(eq, "joint", joint1=j.name, joint2=m["joint"],
                          polycoef=fmt((m.get("offset", 0.0), m.get("multiplier", 1.0), 0, 0, 0)))

    act = ET.SubElement(root, "actuator")
    ctrl_joints = []
    for j in robot.moving_joints():
        a = j.actuator
        if a.get("kind", "none") == "none" or j.mimic:
            continue
        if a["kind"] == "velocity":  # drive wheels: ctrl is a joint speed (rad/s or m/s)
            vel = dict(name=j.name, joint=j.name, kv=f"{a.get('kv', 1.0):.6g}")
            if j.effort:
                vel["forcerange"] = fmt((-j.effort, j.effort))
            ET.SubElement(act, "velocity", vel)
            ctrl_joints.append(None)
            continue
        ctrl_joints.append(j.name)
        attrs = dict(name=j.name, joint=j.name, kp=f"{a['kp']:.6g}", kv=f"{a.get('kv', 0):.6g}")
        if j.type != "continuous":
            attrs["ctrlrange"] = fmt((j.lower, j.upper))
        if j.effort:
            attrs["forcerange"] = fmt((-j.effort, j.effort))
        ET.SubElement(act, "position", attrs)

    if keyframes:
        kf = ET.SubElement(root, "keyframe")
        order = [j.name for j in _joint_order(robot)]
        root_q = list(robot.links[robot.root].origin) + [1, 0, 0, 0] if robot.floating_base and floating else []
        for kname, q in keyframes.items():
            qpos = root_q + [q.get(n, 0.0) for n in order]
            ctrl = [q.get(n, 0.0) if n else 0.0 for n in ctrl_joints]
            ET.SubElement(kf, "key", name=kname, qpos=fmt(qpos), ctrl=fmt(ctrl))

    ET.indent(root)
    return ET.ElementTree(root)


def _joint_order(robot: Robot):
    """Joints in MJCF depth-first body order (== qpos order)."""
    return robot.moving_joints()


def write_mjcf(robot: Robot, path: Path, **kw) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    build_mjcf(robot, **kw).write(path, encoding="unicode")


def expand_mimic(robot: Robot, q: dict[str, float]) -> dict[str, float]:
    q = dict(q)
    for j in robot.joints.values():
        if j.mimic and j.mimic["joint"] in q:
            q[j.name] = q[j.mimic["joint"]] * j.mimic.get("multiplier", 1.0) + j.mimic.get("offset", 0.0)
    return q


# pairs closer than this count as touching (PyBullet/PhysX contact margins see flush parts as colliding)
TOUCH_MARGIN = 1e-3


def collision_matrix(robot: Robot, mesh_dir: Path, samples: int = 5000, seed: int = 0):
    with tempfile.TemporaryDirectory() as tmp:
        xml_path = Path(tmp) / "probe.xml"
        build_mjcf(robot, meshdir=str(mesh_dir.resolve()), floor=False, filterparent=False,
                   collision_only=True, floating=False).write(xml_path, encoding="unicode")
        model = mujoco.MjModel.from_xml_path(str(xml_path))
    model.geom_margin[:] = TOUCH_MARGIN  # report near-contacts too
    data = mujoco.MjData(model)
    joints = _joint_order(robot)
    body_name = [mujoco.mj_id2name(model, mujoco.mjtObj.mjOBJ_BODY, i) for i in range(model.nbody)]

    def contacts(q: dict[str, float]) -> set[tuple[str, str]]:
        q = expand_mimic(robot, q)
        data.qpos[:] = [q.get(j.name, 0.0) for j in joints]
        mujoco.mj_kinematics(model, data)
        mujoco.mj_collision(model, data)
        pairs = set()
        for c in data.contact[: data.ncon]:
            if c.dist < TOUCH_MARGIN:  # touching or within the margin other engines use
                a = body_name[model.geom_bodyid[c.geom1]]
                b = body_name[model.geom_bodyid[c.geom2]]
                pairs.add(tuple(sorted((a, b))))
        return pairs

    rng = np.random.default_rng(seed)
    default = contacts({})
    counts: Counter = Counter()
    free = [j for j in joints if not j.mimic]
    for _ in range(samples):
        q = {j.name: rng.uniform(*((-np.pi, np.pi) if j.type == "continuous" else (j.lower, j.upper)))
             for j in free}
        counts.update(contacts(q))

    adjacent = {tuple(sorted((j.parent, j.child))) for j in robot.joints.values()}
    result = {}
    for pair in itertools.combinations(sorted(robot.links), 2):
        if pair in adjacent:
            result[pair] = "Adjacent"
        elif pair in default:
            result[pair] = "Default"
        elif counts[pair] >= 0.95 * samples:
            result[pair] = "Always"
        elif counts[pair] == 0:
            result[pair] = "Never"
    stats = {"samples": samples, "pairs_seen_colliding": {f"{a}|{b}": n for (a, b), n in sorted(counts.items())}}
    return result, stats


def build_srdf(robot: Robot, disabled: dict[tuple[str, str], str]) -> ET.ElementTree:
    s = robot.spec.get("srdf") or {}
    s.setdefault("virtual_joint", {"name": "world_joint", "type": "floating" if robot.floating_base else "fixed",
                                   "parent_frame": "world", "child_link": robot.root})
    s.setdefault("passive_joints", [j.name for j in robot.moving_joints()
                                    if j.actuator.get("kind", "none") == "none" and not j.mimic])
    root = ET.Element("robot", name=robot.name)
    root.append(ET.Comment(" generated by cad2urdf; collision matrix sampled on collision geometry "))
    for gname, g in s.get("groups", {}).items():
        ge = ET.SubElement(root, "group", name=gname)
        if "chain" in g:
            ET.SubElement(ge, "chain", base_link=g["chain"][0], tip_link=g["chain"][1])
        for j in g.get("joints", []):
            ET.SubElement(ge, "joint", name=j)
        for l in g.get("links", []):
            ET.SubElement(ge, "link", name=l)
    for sname, st in s.get("group_states", {}).items():
        se = ET.SubElement(root, "group_state", name=sname, group=st["group"])
        for j, v in st["joints"].items():
            ET.SubElement(se, "joint", name=j, value=f"{v:.6g}")
    ee = s.get("end_effector")
    if ee:
        ET.SubElement(root, "end_effector", name=ee["name"], parent_link=ee["parent_link"], group=ee["group"],
                      parent_group=ee["parent_group"])
    vj = s.get("virtual_joint")
    if vj:
        ET.SubElement(root, "virtual_joint", name=vj["name"], type=vj["type"], parent_frame=vj["parent_frame"],
                      child_link=vj["child_link"])
    for pj in s.get("passive_joints", []):
        ET.SubElement(root, "passive_joint", name=pj)
    for (a, b), reason in sorted(disabled.items(), key=lambda kv: (kv[1], kv[0])):
        ET.SubElement(root, "disable_collisions", link1=a, link2=b, reason=reason)
    ET.indent(root)
    return ET.ElementTree(root)


def _actuated(robot: Robot):
    return [j for j in robot.moving_joints() if j.actuator.get("kind", "none") != "none"]


def _home(robot: Robot) -> dict[str, float]:
    """Joint positions of the SRDF "home" state (0 for unspecified joints, mimics expanded)."""

    home = robot.spec.get("srdf", {}).get("group_states", {}).get("home", {}).get("joints", {})
    return expand_mimic(robot, {j.name: home.get(j.name, 0.0) for j in robot.moving_joints()})


def isaaclab_cfg(robot: Robot, urdf_rel: str) -> str:
    home = _home(robot)
    lines = [
        f'"""Isaac Lab ArticulationCfg for {robot.name} (generated by cad2urdf)."""',
        "",
        "import os",
        "",
        "import isaaclab.sim as sim_utils",
        "from isaaclab.actuators import ImplicitActuatorCfg",
        "from isaaclab.assets.articulation import ArticulationCfg",
        "",
        "_HERE = os.path.dirname(__file__)",
        "",
        f"{robot.name.upper()}_CFG = ArticulationCfg(",
        "    spawn=sim_utils.UrdfFileCfg(",
        f'        asset_path=os.path.join(_HERE, "{urdf_rel}"),',
        f"        fix_base={not robot.floating_base},",
        "        merge_fixed_joints=True,",
        "        # Collision comes from the URDF <collision> elements, which cad2urdf already made",
        "        # convex (primitives / <=64-vertex hulls). The importer then only has to cook them.",
        "        collision_from_visuals=False,",
        '        collision_type="Convex Hull",',
        "        self_collision=True,  # pairs to filter: see the SRDF disable_collisions list",
        "        joint_drive=sim_utils.UrdfConverterCfg.JointDriveCfg(",
        '            drive_type="force",',
        '            target_type="position",',
        "            gains=sim_utils.UrdfConverterCfg.JointDriveCfg.PDGainsCfg(stiffness=0.0, damping=0.0),",
        "        ),",
        "    ),",
        "    init_state=ArticulationCfg.InitialStateCfg(",
        "        joint_pos={" + ", ".join(f'"{k}": {v:.4g}' for k, v in home.items()) + "},",
        "    ),",
        "    actuators={",
    ]
    for j in robot.moving_joints():
        a = j.actuator
        if a.get("kind", "none") == "none" and not j.mimic:
            continue
        kp, kv = (a.get("kp", 0.0), a.get("kv", 0.0)) if a.get("kind") != "none" else (0.0, 0.0)
        lines += [
            f'        "{j.name}": ImplicitActuatorCfg(',
            f'            joint_names_expr=["{j.name}"],',
            f"            stiffness={kp:.6g},",
            f"            damping={kv:.6g},",
            f"            armature={j.armature:.6g},",
            f"            friction={j.friction:.6g},",
            *([f"            joint_effort_limit={j.effort:.6g},"] if j.effort else []),
            *([f"            joint_velocity_limit={j.velocity:.6g},"] if j.velocity else []),
            "        ),",
        ]
    lines += ["    },", ")", ""]
    return "\n".join(lines)


def _groups(robot: Robot):
    """Split actuated joints into a plain PD group and one group per mimic leader."""
    act = _actuated(robot)
    followers = [j for j in robot.moving_joints() if j.mimic]
    leaders = {j.mimic["joint"] for j in followers}
    plain = [j for j in act if j.name not in leaders and not j.mimic]
    mimic_groups = [(robot.joints[l], [f for f in followers if f.mimic["joint"] == l]) for l in sorted(leaders)]
    return plain, mimic_groups


def _force(j) -> float:
    return j.effort if j.effort else 1e10  # ManiSkill's default "unlimited"


def maniskill_agent(robot: Robot, urdf_rel: str) -> str:

    plain, mimic_groups = _groups(robot)
    fr = robot.spec.get("contact", {}).get("friction", [1.0])[0]
    states = robot.spec.get("srdf", {}).get("group_states", {})
    order = [j.name for j in robot.moving_joints()]  # == SAPIEN active-joint order
    kf = []
    for name, st in states.items():
        q = expand_mimic(robot, {**{n: 0.0 for n in order}, **st["joints"]})
        kf.append(f'        {name}=Keyframe(qpos=np.array([{", ".join(f"{q[n]:.4g}" for n in order)}]), pose=sapien.Pose()),')
    body = []
    if plain:
        body += [
            "        arm = PDJointPosControllerConfig(",
            f"            {[j.name for j in plain]},",
            "            lower=None, upper=None,",
            f"            stiffness={[j.actuator.get('kp', 0.0) for j in plain]},",
            f"            damping={[j.actuator.get('kv', 0.0) for j in plain]},",
            f"            force_limit={[_force(j) for j in plain]},",
            "            normalize_action=False,",
            "        )",
        ]
    names = ["arm"] if plain else []
    for i, (lead, fol) in enumerate(mimic_groups):
        g = "gripper" if len(mimic_groups) == 1 else f"mimic_{lead.name}"
        names.append(g)
        mimic_map = {f.name: {"joint": lead.name, "multiplier": f.mimic.get("multiplier", 1.0),
                              "offset": f.mimic.get("offset", 0.0)} for f in fol}
        body += [
            f"        {g} = PDJointPosMimicControllerConfig(",
            f"            {[lead.name] + [f.name for f in fol]},",
            f"            lower={lead.lower}, upper={lead.upper},",
            f"            stiffness={lead.actuator.get('kp', 0.0)}, damping={lead.actuator.get('kv', 0.0)},",
            f"            force_limit={_force(lead)},",
            f"            mimic={mimic_map},",
            "            normalize_action=False,  # targets in joint units (rad / m), not [-1, 1]",
            "        )",
        ]
    body.append(f"        return dict(pd_joint_pos=dict({', '.join(f'{n}={n}' for n in names)}))")
    return "\n".join([
        f'"""ManiSkill 3 agent for {robot.name} (generated by cad2urdf)."""',
        "",
        "import os",
        "",
        "import numpy as np",
        "import sapien",
        "",
        "from mani_skill.agents.base_agent import BaseAgent, Keyframe",
        "from mani_skill.agents.controllers import PDJointPosControllerConfig, PDJointPosMimicControllerConfig",
        "from mani_skill.agents.registration import register_agent",
        "",
        "",
        "@register_agent()",
        f"class {''.join(w.capitalize() for w in robot.name.split('_'))}(BaseAgent):",
        f'    uid = "{robot.name}"',
        f'    urdf_path = os.path.join(os.path.dirname(__file__), "{urdf_rel}")',
        "    # SAPIEN reads the SRDF next to the URDF automatically, but only reason=\"Default\" pairs.",
        "    load_multiple_collisions = False  # every collision STL is already a single convex piece",
        f"    fix_root_link = {not robot.floating_base}",
        "    urdf_config = dict(",
        f"        _materials=dict(default=dict(static_friction={fr}, dynamic_friction={fr}, restitution=0.0)),",
        "        link={" + ", ".join(f'"{l}": dict(material="default")' for l in robot.links) + "},",
        "    )",
        "    keyframes = dict(",
        *kf,
        "    )",
        "",
        "    @property",
        "    def _controller_configs(self):",
        *body,
        "",
    ])


def gazebo_controllers(robot: Robot) -> str:
    plain, mimic_groups = _groups(robot)
    lines = [
        "# ros2_control controllers for gz_ros2_control (generated by cad2urdf)",
        "controller_manager:",
        "  ros__parameters:",
        "    update_rate: 500",
        "    joint_state_broadcaster: {type: joint_state_broadcaster/JointStateBroadcaster}",
    ]
    if plain:
        lines.append("    arm_controller: {type: joint_trajectory_controller/JointTrajectoryController}")
    for lead, _ in mimic_groups:
        lines.append(f"    {lead.name}_controller: {{type: position_controllers/GripperActionController}}")
    if plain:
        lines += ["", "arm_controller:", "  ros__parameters:", f"    joints: [{', '.join(j.name for j in plain)}]",
                  "    command_interfaces: [position]", "    state_interfaces: [position, velocity]"]
    for lead, _ in mimic_groups:
        lines += ["", f"{lead.name}_controller:", "  ros__parameters:", f"    joint: {lead.name}"]
    return "\n".join(lines) + "\n"


def write_targets(robot: Robot, out: Path) -> None:
    (out / "isaaclab").mkdir(parents=True, exist_ok=True)
    (out / "maniskill").mkdir(parents=True, exist_ok=True)
    (out / "gazebo" / "config").mkdir(parents=True, exist_ok=True)
    (out / "isaaclab" / f"{robot.name}_cfg.py").write_text(isaaclab_cfg(robot, f"../{robot.name}.urdf"))
    (out / "maniskill" / f"{robot.name}_agent.py").write_text(maniskill_agent(robot, f"../{robot.name}.urdf"))
    (out / "gazebo" / "config" / "controllers.yaml").write_text(gazebo_controllers(robot))
