"""ManiSkill 3 agent for arm4 (generated by cad2urdf)."""

import os

import numpy as np
import sapien

from mani_skill.agents.base_agent import BaseAgent, Keyframe
from mani_skill.agents.controllers import PDJointPosControllerConfig, PDJointPosMimicControllerConfig
from mani_skill.agents.registration import register_agent


@register_agent()
class Arm4(BaseAgent):
    uid = "arm4"
    urdf_path = os.path.join(os.path.dirname(__file__), "../arm4.urdf")
    # SAPIEN reads the SRDF next to the URDF automatically, but only reason="Default" pairs.
    load_multiple_collisions = False  # every collision STL is already a single convex piece
    fix_root_link = True
    urdf_config = dict(
        _materials=dict(default=dict(static_friction=1.0, dynamic_friction=1.0, restitution=0.0)),
        link={"base_link": dict(material="default"), "turret": dict(material="default"), "upper_arm": dict(material="default"), "forearm": dict(material="default"), "gripper_base": dict(material="default"), "finger_left": dict(material="default"), "finger_right": dict(material="default")},
    )
    keyframes = dict(
        home=Keyframe(qpos=np.array([0, 0, 0, 0, 0, 0]), pose=sapien.Pose()),
        ready=Keyframe(qpos=np.array([0, 0.6, 1.2, 0, 0, 0]), pose=sapien.Pose()),
        open=Keyframe(qpos=np.array([0, 0, 0, 0, 0.008, 0.008]), pose=sapien.Pose()),
        closed=Keyframe(qpos=np.array([0, 0, 0, 0, -0.006, -0.006]), pose=sapien.Pose()),
    )

    @property
    def _controller_configs(self):
        arm = PDJointPosControllerConfig(
            ['shoulder_yaw', 'shoulder_pitch', 'elbow', 'wrist_roll'],
            lower=None, upper=None,
            stiffness=[200.0, 200.0, 200.0, 20.0],
            damping=[10.0, 10.0, 10.0, 1.0],
            force_limit=[40, 40, 20, 5],
            normalize_action=False,
        )
        gripper = PDJointPosMimicControllerConfig(
            ['finger_left', 'finger_right'],
            lower=-0.006, upper=0.008,
            stiffness=500.0, damping=20.0,
            force_limit=20,
            mimic={'finger_right': {'joint': 'finger_left', 'multiplier': 1.0, 'offset': 0.0}},
            normalize_action=False,  # targets in joint units (rad / m), not [-1, 1]
        )
        return dict(pd_joint_pos=dict(arm=arm, gripper=gripper))
